//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theaters
    {
        public Nullable<int> movie_number { get; set; }
        public int id { get; set; }
        public string avail_seats_arr { get; set; }
        public Nullable<int> hall_num { get; set; }
    
        public virtual Movies Movies { get; set; }
    }
}
